name: Go Tests

on: [push, pull_request]

env:
  GO111MODULE: on

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Run tests
      run: make test-go
